version: '3.8'

services:
  telegram-auto-forward:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=develop_docker
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - APP_YOUR_PHONE=${APP_YOUR_PHONE}
      - DESTINATION_CHANNEL_ID=${DESTINATION_CHANNEL_ID}
      - SOURCE_CHANNEL_ID=${SOURCE_CHANNEL_ID}
      - SOURCE_CHANNEL_IDS=${SOURCE_CHANNEL_IDS}
      - DESTINATION_CHANNEL_IDS=${DESTINATION_CHANNEL_IDS}
      - RESPONSE_CHANNEL_ID=${RESPONSE_CHANNEL_ID}
      - APP_YOUR_PWD=${APP_YOUR_PWD}
      - API_ENDPOINT_1=${API_ENDPOINT_1}
      - API_ENDPOINT_2=${API_ENDPOINT_2}
      - API_ENDPOINT_3=${API_ENDPOINT_3}
      - API_ENDPOINT_4=${API_ENDPOINT_4}
      - PLATFORM_TYPE=${PLATFORM_TYPE}
      - DEVICE_CODE=${DEVICE_CODE}
      - SIGN=${SIGN}
      - BASE_URL=http://localhost:5100
      - H25_USER=manus9331
      - H25_PASSWORD=nnnn9331
      - T6_USER=Arun0011
      - T6_PASSWORD=Arun0011
      - URL_LOGIN_APP=${URL_LOGIN_APP}
      - URL_LOGIN_WEB=${URL_LOGIN_WEB}
      - BOT_RESULT_CHANNEL_ID=${BOT_RESULT_CHANNEL_ID}
    volumes:
      - .:/usr/src/app
      - ./sessions:/usr/src/app/sessions
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f ${BASE_URL} || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
