[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
runtime = "V2"
numReplicas = 1
healthcheckPath = "/health"
sleepApplication = true
useLegacyStacker = false
restartPolicyType = "ON_FAILURE"
healthcheckTimeout = 300
restartPolicyMaxRetries = 10

# üåè Multi-region config (‡πÄ‡∏Ç‡∏µ‡∏¢‡∏ô‡πÅ‡∏ö‡∏ö table ‡∏õ‡∏•‡∏≠‡∏î‡∏†‡∏±‡∏¢)
[deploy.multiRegionConfig]
region = "asia-southeast1-eqsg3a"
numReplicas = 1
